# Generated by Django 2.1.1 on 2018-09-02 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter First Name of Student', max_length=20)),
                ('last_name', models.CharField(help_text='Enter Last Name of Student', max_length=20)),
                ('phone', models.CharField(help_text='Enter Phone of Student', max_length=20)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a ticket name', max_length=10)),
                ('price', models.IntegerField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('p', 'permanent'), ('o', 'one_time')], default='o', help_text='Choise type of ticket', max_length=1)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.DeleteModel(
            name='Filial',
        ),
        migrations.DeleteModel(
            name='Organisation',
        ),
        migrations.AddField(
            model_name='student',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='observer.Ticket'),
        ),
    ]
