# Generated by Django 2.1.1 on 2018-09-12 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0007_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='observer.Filial'),
        ),
        migrations.AddField(
            model_name='section',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='observer.Filial'),
        ),
        migrations.AddField(
            model_name='student',
            name='filial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='observer.Filial'),
        ),
    ]
